In [ ]:
# Computing network FC matrices I want to use as predictors in my model


In [1]:
# First create a dictionary containing all ROIs per network

import pandas as pd

# Define the file path again and load the data
file_path = 'Schaefer2018_400_17N_Tian32_Buckner7hemi_FSLMNI152_2mm_labels.csv'
fc_data_info = pd.read_csv(file_path)

# Initialize dictionary to store the ROI indices for each network
networks_of_interest = {
    "default mode network": ["DefaultA", "DefaultB", "DefaultC"],
    "salience network": ["SalVentAttnA", "SalVentAttnB"],
    "frontoparietal control network": ["ContA", "ContB", "ContC"],
    "limbic network": ["LimbicA", "LimbicB"],
    "dorsal attention network": ["DorsAttnA", "DorsAttnB"]
}

# Initialize dictionary to store the ROI indices for each network
network_rois = {network: [] for network in networks_of_interest}

# Loop through each ROI and assign to the correct network based on the ROI name
for index, row in fc_data_info.iterrows():
    roi_name = row["ROI Name"]
    roi_index = row["ROI Label"] 
    
    for network, keywords in networks_of_interest.items():
        if any(keyword in roi_name for keyword in keywords):
            network_rois[network].append(roi_index)

# initializing limbic system ROIs lists (both included and excluded)
limbic_included = [401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 412, 413, 415,
                   417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 428, 429, 431]
limbic_excluded = [411, 414, 416, 427, 430, 432]

# Append included ROIs to the limbic network
network_rois["limbic network"].extend(limbic_included)

# Display the resulting dictionaries for the limbic network and all network ROIs
network_rois, limbic_included, limbic_excluded


({'default mode network': [149,
   150,
   151,
   152,
   153,
   154,
   155,
   156,
   157,
   158,
   159,
   160,
   161,
   162,
   163,
   164,
   165,
   166,
   167,
   168,
   169,
   170,
   171,
   172,
   173,
   174,
   175,
   176,
   177,
   178,
   179,
   180,
   181,
   182,
   183,
   184,
   185,
   186,
   187,
   188,
   189,
   190,
   191,
   192,
   193,
   194,
   358,
   359,
   360,
   361,
   362,
   363,
   364,
   365,
   366,
   367,
   368,
   369,
   370,
   371,
   372,
   373,
   374,
   375,
   376,
   377,
   378,
   379,
   380,
   381,
   382,
   383,
   384,
   385,
   386,
   387,
   388,
   389,
   390],
  'salience network': [86,
   87,
   88,
   89,
   90,
   91,
   92,
   93,
   94,
   95,
   96,
   97,
   98,
   99,
   100,
   101,
   102,
   103,
   104,
   105,
   106,
   107,
   108,
   285,
   286,
   287,
   288,
   289,
   290,
   291,
   292,
   293,
   294,
   295,
   296,
   297,
   298,
   299,
   300,
   301,
   302,
   303,
 

In [ ]:
# Function for computing FC matrices of specific networks

import numpy as np
import os

def compute_network_fc_matrices(network_name, input_dir='full FC matrices', output_dir='Network FC matrices'):
    """
    Computes the FC matrices for a specific network across all participants and saves them
    in a folder named after the network, preserving the input subdirectory structure.
    
    Parameters:
    network_name (str): Name of the network (e.g., 'default' for Default Mode Network).
    input_dir (str): Base directory containing full FC matrix files with subdirectories for each run.
    output_dir (str): Base directory to save network-specific FC matrices, organized by network name.
    """
    # Ensure the network_rois dictionary is loaded
    if 'network_rois' not in globals():
        raise ValueError("The network_rois dictionary with ROI indices for each network is not loaded.")
    
    # Get the ROI indices for the specified network
    if network_name not in network_rois:
        raise ValueError(f"Network '{network_name}' not found in predefined networks.")
    roi_indices = network_rois[network_name]
    
    # Define the specific output directory for this network 
    network_output_base_dir = os.path.join(output_dir, network_name.lower())
    os.makedirs(network_output_base_dir, exist_ok=True)
    
    # Walk through each subdirectory and file in the input directory
    for root, _, files in os.walk(input_dir):
        for filename in files:
            if filename.endswith('_full_FC_matrix.npy'):
                # Construct the full path to the input FC matrix file
                full_fc_path = os.path.join(root, filename)
                
                # Load the full FC matrix
                full_fc_matrix = np.load(full_fc_path)
                
                # Extract the submatrix for the specified network
                network_fc_matrix = full_fc_matrix[np.ix_(roi_indices, roi_indices)]
                
                # Extract the full participant ID from the filename
                participant_id = filename.split('_full_FC_matrix.npy')[0]
                
                # Preserve the subdirectory structure within the network's output folder
                relative_subdir = os.path.relpath(root, input_dir)
                output_subdir = os.path.join(network_output_base_dir, relative_subdir)
                os.makedirs(output_subdir, exist_ok=True)
                
                # Generate the output filename and path within the correct subdirectory
                output_filename = f"{participant_id}_{network_name.split()[0].lower()}_FC_matrix.npy"
                output_path = os.path.join(output_subdir, output_filename)
                
                # Save the network-specific FC matrix
                np.save(output_path, network_fc_matrix)
                print(f"Saved {output_filename} in {output_subdir}")



In [ ]:
# Compute default mode network FC matrices
compute_network_fc_matrices("default mode network")

In [12]:
# Compute salience network FC matrices
compute_network_fc_matrices("salience network")

Saved NDAR_INVAG023WG3_salience_FC_matrix.npy in Network FC matrices\salience network\hammer_AP_run01
Saved NDAR_INVAG388HJL_salience_FC_matrix.npy in Network FC matrices\salience network\hammer_AP_run01
Saved NDAR_INVAG900RVD_salience_FC_matrix.npy in Network FC matrices\salience network\hammer_AP_run01
Saved NDAR_INVAH529JMM_salience_FC_matrix.npy in Network FC matrices\salience network\hammer_AP_run01
Saved NDAR_INVAK834VNU_salience_FC_matrix.npy in Network FC matrices\salience network\hammer_AP_run01
Saved NDAR_INVAL101MH2_salience_FC_matrix.npy in Network FC matrices\salience network\hammer_AP_run01
Saved NDAR_INVAP729WCD_salience_FC_matrix.npy in Network FC matrices\salience network\hammer_AP_run01
Saved NDAR_INVAT097DFG_salience_FC_matrix.npy in Network FC matrices\salience network\hammer_AP_run01
Saved NDAR_INVAZ218MB7_salience_FC_matrix.npy in Network FC matrices\salience network\hammer_AP_run01
Saved NDAR_INVBD216MCC_salience_FC_matrix.npy in Network FC matrices\salience netw

In [15]:
# Compute frontoparietal control network FC matrices
compute_network_fc_matrices("frontoparietal control network")

Saved NDAR_INVAG023WG3_frontoparietal_FC_matrix.npy in Network FC matrices\frontoparietal control network\hammer_AP_run01
Saved NDAR_INVAG388HJL_frontoparietal_FC_matrix.npy in Network FC matrices\frontoparietal control network\hammer_AP_run01
Saved NDAR_INVAG900RVD_frontoparietal_FC_matrix.npy in Network FC matrices\frontoparietal control network\hammer_AP_run01
Saved NDAR_INVAH529JMM_frontoparietal_FC_matrix.npy in Network FC matrices\frontoparietal control network\hammer_AP_run01
Saved NDAR_INVAK834VNU_frontoparietal_FC_matrix.npy in Network FC matrices\frontoparietal control network\hammer_AP_run01
Saved NDAR_INVAL101MH2_frontoparietal_FC_matrix.npy in Network FC matrices\frontoparietal control network\hammer_AP_run01
Saved NDAR_INVAP729WCD_frontoparietal_FC_matrix.npy in Network FC matrices\frontoparietal control network\hammer_AP_run01
Saved NDAR_INVAT097DFG_frontoparietal_FC_matrix.npy in Network FC matrices\frontoparietal control network\hammer_AP_run01
Saved NDAR_INVAZ218MB7_f

In [8]:
# Compute limbic network FC matrices
compute_network_fc_matrices("limbic network")

Saved NDAR_INVAG023WG3_limbic_FC_matrix.npy in Network FC matrices\limbic network\hammer_AP_run01
Saved NDAR_INVAG388HJL_limbic_FC_matrix.npy in Network FC matrices\limbic network\hammer_AP_run01
Saved NDAR_INVAG900RVD_limbic_FC_matrix.npy in Network FC matrices\limbic network\hammer_AP_run01
Saved NDAR_INVAH529JMM_limbic_FC_matrix.npy in Network FC matrices\limbic network\hammer_AP_run01
Saved NDAR_INVAK834VNU_limbic_FC_matrix.npy in Network FC matrices\limbic network\hammer_AP_run01
Saved NDAR_INVAL101MH2_limbic_FC_matrix.npy in Network FC matrices\limbic network\hammer_AP_run01
Saved NDAR_INVAP729WCD_limbic_FC_matrix.npy in Network FC matrices\limbic network\hammer_AP_run01
Saved NDAR_INVAT097DFG_limbic_FC_matrix.npy in Network FC matrices\limbic network\hammer_AP_run01
Saved NDAR_INVAZ218MB7_limbic_FC_matrix.npy in Network FC matrices\limbic network\hammer_AP_run01
Saved NDAR_INVBD216MCC_limbic_FC_matrix.npy in Network FC matrices\limbic network\hammer_AP_run01
Saved NDAR_INVBH217X

In [17]:
# Compute dorsal attention network FC matrices
compute_network_fc_matrices("dorsal attention network")

Saved NDAR_INVAG023WG3_dorsal_FC_matrix.npy in Network FC matrices\dorsal attention network\hammer_AP_run01
Saved NDAR_INVAG388HJL_dorsal_FC_matrix.npy in Network FC matrices\dorsal attention network\hammer_AP_run01
Saved NDAR_INVAG900RVD_dorsal_FC_matrix.npy in Network FC matrices\dorsal attention network\hammer_AP_run01
Saved NDAR_INVAH529JMM_dorsal_FC_matrix.npy in Network FC matrices\dorsal attention network\hammer_AP_run01
Saved NDAR_INVAK834VNU_dorsal_FC_matrix.npy in Network FC matrices\dorsal attention network\hammer_AP_run01
Saved NDAR_INVAL101MH2_dorsal_FC_matrix.npy in Network FC matrices\dorsal attention network\hammer_AP_run01
Saved NDAR_INVAP729WCD_dorsal_FC_matrix.npy in Network FC matrices\dorsal attention network\hammer_AP_run01
Saved NDAR_INVAT097DFG_dorsal_FC_matrix.npy in Network FC matrices\dorsal attention network\hammer_AP_run01
Saved NDAR_INVAZ218MB7_dorsal_FC_matrix.npy in Network FC matrices\dorsal attention network\hammer_AP_run01
Saved NDAR_INVBD216MCC_dorsa

In [ ]:
# Checking if all participants' fMRI files are succesfully constructed
# 

import pandas as pd
import os

# Load the behavioral data to get the list of participant IDs
behavioral_file_path = 'behavioral_no_missing/behavioral_no_missing.csv'
behavioral_data = pd.read_csv(behavioral_file_path)

# Extract unique participant IDs from the behavioral data
participant_ids = set(behavioral_data['participant_id'].unique())

# Define the base directory for the network-specific FC matrices
network_fc_matrices_dir = 'Network FC matrices/default mode network'

# Initialize a dictionary to store folder-wise file count and any missing IDs
folder_check = {}

# Walk through each subdirectory in the network FC matrices folder
for root, dirs, files in os.walk(network_fc_matrices_dir):
    if files:  # Only consider folders with files
        # Check if each participant_id from the behavioral file is present in any file name
        missing_ids = {pid for pid in participant_ids if not any(pid in filename for filename in files)}
        
        # Store information about file count and missing IDs for each folder
        folder_check[root] = {
            'file_count': len(files),
            'missing_ids': missing_ids if missing_ids else "None",
            'all_ids_present': len(missing_ids) == 0,
            'exact_file_count': len(files) == 172
        }

# Convert the folder_check dictionary to a DataFrame for review
folder_check_df = pd.DataFrame(folder_check).transpose()
folder_check_df.reset_index(inplace=True)
folder_check_df.columns = ["Folder", "File Count", "Missing IDs", "All IDs Present", "Exact File Count"]

# Display the DataFrame
print(folder_check_df)


                                              Folder File Count Missing IDs  \
0  Network FC matrices/default mode network\hamme...        172        None   
1  Network FC matrices/default mode network\rest_...        172        None   
2  Network FC matrices/default mode network\rest_...        172        None   
3  Network FC matrices/default mode network\rest_...        172        None   
4  Network FC matrices/default mode network\rest_...        172        None   
5  Network FC matrices/default mode network\stroo...        172        None   
6  Network FC matrices/default mode network\stroo...        172        None   

  All IDs Present Exact File Count  
0            True             True  
1            True             True  
2            True             True  
3            True             True  
4            True             True  
5            True             True  
6            True             True  


In [ ]:
# Check single FC matrix file

import numpy as np

def display_fmri_file_details(file_path):
    """
    Loads an fMRI file (FC matrix) and displays key details for confirmation.
    
    Parameters:
    file_path (str): The path to the fMRI file to be examined.
    """
    # Load the FC matrix
    fc_matrix = np.load(file_path)
    
    # Display important details
    print("File Path:", file_path)
    print("Matrix Shape:", fc_matrix.shape)
    print("Example Values (Top-left 5x5 section):")
    print(fc_matrix[:5, :5])  # Display a 5x5 section for an overview

# Example usage
file_path = 'Network FC matrices/limbic network/rest_AP_run01/NDAR_INVAG023WG3_limbic_FC_matrix.npy'  
display_fmri_file_details(file_path)

# Showing 79x79 as expected with 79 ROIs for default mode network, nice!
# For limbic system showing 50x50 as expected after addition of Tian Atlas ROIs


File Path: Network FC matrices/limbic network/rest_AP_run01/NDAR_INVAG023WG3_limbic_FC_matrix.npy
Matrix Shape: (50, 50)
Example Values (Top-left 5x5 section):
[[ 1.         -0.16369355 -0.1168652  -0.31515568  0.18620624]
 [-0.16369355  1.          0.07951839  0.21233962  0.18604113]
 [-0.1168652   0.07951839  1.          0.21619189  0.00136214]
 [-0.31515568  0.21233962  0.21619189  1.         -0.0080893 ]
 [ 0.18620624  0.18604113  0.00136214 -0.0080893   1.        ]]
